sudo: required
services: 
    - docker

before_install:
    - docker build -t iseniori/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run iseniori/react-test npm test -- --coverage

after_success:
    - docker build -t iseniori/multi-client ./client
    - docker build -t iseniori/multi-nginx ./nginx
    - docker build -t iseniori/multi-server ./server
    - docker build -t iseniori/multi-worker ./worker
#Login to docker CLI    
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take images and pust them to Docker hub
    - docker push iseniori/multi-client
    - docker push iseniori/multi-nginx
    - docker push iseniori/multi-server
    - docker push iseniori/multi-worker
    